// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO links(id,createdAt,updatedAt,longUrl,short,accessCount)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    0
)
RETURNING id,createdAt,updatedAt,longUrl,short
`

type CreateUrlParams struct {
	Longurl string
	Short   string
}

type CreateUrlRow struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Longurl   string
	Short     string
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (CreateUrlRow, error) {
	row := q.db.QueryRowContext(ctx, createUrl, arg.Longurl, arg.Short)
	var i CreateUrlRow
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Longurl,
		&i.Short,
	)
	return i, err
}
