// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete.sql

package database

import (
	"context"
)

const deleteUrl = `-- name: DeleteUrl :exec
DELETE FROM links WHERE short = $1
`

func (q *Queries) DeleteUrl(ctx context.Context, short string) error {
	_, err := q.db.ExecContext(ctx, deleteUrl, short)
	return err
}
