// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getUrl = `-- name: GetUrl :one
SELECT id,createdAt,updatedAt,longUrl,short FROM links WHERE short = $1
`

type GetUrlRow struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Longurl   string
	Short     sql.NullString
}

func (q *Queries) GetUrl(ctx context.Context, short sql.NullString) (GetUrlRow, error) {
	row := q.db.QueryRowContext(ctx, getUrl, short)
	var i GetUrlRow
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Longurl,
		&i.Short,
	)
	return i, err
}
