// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getCounts.sql

package database

import (
	"context"
)

const getCounts = `-- name: GetCounts :one
SELECT id, longurl, short, createdat, updatedat, accesscount FROM links WHERE short = $1
`

func (q *Queries) GetCounts(ctx context.Context, short string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getCounts, short)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Longurl,
		&i.Short,
		&i.Createdat,
		&i.Updatedat,
		&i.Accesscount,
	)
	return i, err
}
