// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: init.sql

package database

import (
	"context"
)

const populateBloom = `-- name: PopulateBloom :many
SELECT short FROM links
`

func (q *Queries) PopulateBloom(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, populateBloom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var short string
		if err := rows.Scan(&short); err != nil {
			return nil, err
		}
		items = append(items, short)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
