// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Link struct {
	ID          uuid.UUID
	Longurl     string
	Short       sql.NullString
	Createdat   time.Time
	Updatedat   time.Time
	Accesscount interface{}
}
