// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUrl = `-- name: UpdateUrl :one
UPDATE links
SET
    longUrl = $1,
    updatedAt = NOW()
WHERE short = $2
RETURNING id,createdAt,updatedAt,longUrl,short
`

type UpdateUrlParams struct {
	Longurl string
	Short   string
}

type UpdateUrlRow struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Longurl   string
	Short     string
}

func (q *Queries) UpdateUrl(ctx context.Context, arg UpdateUrlParams) (UpdateUrlRow, error) {
	row := q.db.QueryRowContext(ctx, updateUrl, arg.Longurl, arg.Short)
	var i UpdateUrlRow
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Longurl,
		&i.Short,
	)
	return i, err
}
